--!strict

local Node = require("node.luau")

type Node = Node.Node

local Tree = {}
Tree.__index = Tree

type Tree = typeof(setmetatable(
	{} :: {
		root: Node?,
	},
	Tree
))

--[[
	Properties of a Red-Black Tree

    Node Color: Each node is either red or black.
    Root Property: The root of the tree is always black.
    Red Property: Red nodes cannot have red children (no two consecutive red nodes on any path).
    Black Property: Every path from a node to its descendant null nodes (leaves) has the same number of black nodes.
    Leaf Property: All leaves (NIL nodes) are black.
]]

function Tree.new()
	return {
		root = nil,
	}
end
